name             'myapp-example'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures myapp-example'
long_description 'Installs/Configures myapp-example'
version          '0.1.0'
